export const SEND_USER_INFO = "SEND_USER_INFO";
export const PUT_USER_INFO = "PUT_USER_INFO";
export const PUT_USER_RESULT = "PUT_USER_RESULT";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USERS_RANKING = "GET_USERS_RANKING";
export const GET_USER_INFO = "GET_USER_INFO";
export const PUT_GAME_LOCAL_TEAM = "PUT_GAME_LOCAL_TEAM";
export const PUT_GAME_AWAY_TEAM = "PUT_GAME_AWAY_TEAM";
export const PUT_GAME_RESULT = "PUT_GAME_RESULT";
export const GET_ALL_GAMES = "GET_ALL_GAMES";
export const GET_ID_GAME = "GET_ID_GAME";
export const GET_ALL_TEAMS = "GET_ALL_TEAMS";
export const GET_ID_TEAM = "GET_ID_TEAM";
export const GET_GROUP_TEAMS = "GET_GROUP_TEAMS";
export const PUT_ID_TEAM = "PUT_ID_TEAM";
export const GET_GROUP_GAMES = "GET_GROUP_GAMES";
export const PUT_GAME_PENALTIES = "PUT_GAME_PENALTIES";

